name: Kedro Diff Package

on:
  push:
    tags:
    - '*'
    branches:
    - 'main'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8,]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      # turning off matrix build for early dev
      # - name: Set up Python ${{ matrix.python-version }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: python -m pip install -e ".[dev]"
      - name: Lint with flake8
        run: flake8 .
      - name: Type check with MyPy
        run: mypy .
      - name: Test with pytest
        run: pytest
  build:
    runs-on: ubuntu-latest
    needs: lint_test
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: python -m pip install -e .
      - name: build
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel
      - name: pypi-publish
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          # PyPI user
          # Password for your PyPI user or an access toke
          password: ${{ secrets.pypi_password }}
          # The repository URL to use
          # repository_url: # optional
          # The target directory for distribution
          # packages_dir: # optional, default is dist
